namespace URLShortener.Application.DTOs.ZibalDTOs
{
    /// <summary>
    /// The Placeholder to Deserialize Zibal's response to Payment creation if you're using the lazy method. 
    /// if you're NOT USING THE LAZY METHOD this information is provided via Query String to your callback address.
    /// </summary>
    public class LazyCallbackResponse
    {
        private string _success = string.Empty;
        /// <summary>
        /// 1 if successful, 0 if fails.
        /// </summary>
        public string Success { get => _success; set => _success = value.Trim(); }

        /// <summary>
        /// Generated By Zibal.
        /// </summary>
        public int TrackID { get; set; }

        private string _orderID = string.Empty;
        /// <summary>
        /// Generated by Merchant, used in reports.
        /// </summary>
        public string OrderID { get => _orderID; set => _orderID = value.Trim(); }

        /// <summary>
        /// this is up to the merchant and doesn't have a value until the transaction is verified by the merchant.
        /// </summary>
        public int? Status { get; set; } = null;

        private string cardNumber = string.Empty;
        /// <summary>
        /// The card number used in the transaction.
        /// </summary>
        public string CardNumber { get => cardNumber; set => cardNumber = value.Trim(); }

        private string hashedCardNumber = string.Empty;
        /// <summary>
        /// Card number used in th transaction but Hashed.
        /// </summary>
        public string HashedCardNumber { get => hashedCardNumber; set => hashedCardNumber = value.Trim(); }
    }

}
