namespace URLShortener.Application.DTOs.ZibalDTOs;

/// <summary>
/// The Placeholder for the response Zibal Sends in response to Payment Verification Request.
/// </summary>
public record ZibalVerifyTransactionResponse
{
    private DateTime paidAt;
    /// <summary>
    /// The exact time when the transaction happened.
    /// </summary>
    public DateTime PaidAt { get => paidAt; set => paidAt = value; }


    private string cardNumber = string.Empty;
    /// <summary>
    /// The Card Number used in the transaction (Masked). e.g: "62741****44"
    /// </summary>
    public string CardNumber { get => cardNumber; set => cardNumber = value; }

    /// <summary>
    /// The Transaction's Status. Check the codes at https://help.zibal.ir/IPG/API/#status-codes.
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// The Amount Paid in Rials.
    /// </summary>
    public long Amount { get; set; }

    /// <summary>
    /// Reference Number of the transaction (in case the transaction was successful).
    /// </summary>
    public int? RefNumber { get; set; }

    /// <summary>
    /// Description of the transaction (in case the transaction was successful).
    /// </summary>
    public string? Description { get; set; }


    private string _orderID = string.Empty;
    /// <summary>
    /// Generated by Merchant, used in reports.
    /// </summary>
    public string OrderID { get => _orderID; set => _orderID = value.Trim(); }

    /// <summary>
    /// Response code regarding the request.
    /// </summary>
    public int Result { get; set; }
    /// <summary>
    /// Response Message provided by Zibal.
    /// </summary>
    public string Message { get; set; } = string.Empty;

}
