namespace URLShortener.Application.Features.Finance.DTOs.Zibal;

/// <summary>
/// The Placeholder for the response zibal sends in response to payment request.
/// </summary>
public sealed record ZibalCreateTransactionResponse
{
    /// <summary>
    /// Generated By Zibal. Sent to Zibal in "Start" Phase.
    /// </summary>
    public int TrackID { get; set; }
    /// <summary>
    /// Response code regarding the request.
    /// </summary>
    public int Result { get; set; }
    /// <summary>
    /// Response Message provided by Zibal.
    /// </summary>
    public string Message { get; set; } = string.Empty;
}
