<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.9" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\URLShortener.Application\URLShortener.Application.csproj" />
    <ProjectReference Include="..\URLShortener.Common\URLShortener.Common.csproj" />
    <ProjectReference Include="..\URLShortener.Persistence\URLShortener.Persistence.csproj" />
  </ItemGroup>

</Project>
