// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using URLShortenerAPI.Data;

#nullable disable

namespace URLShortener.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426050536_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("URLCategoryModelURLModel", b =>
                {
                    b.Property<long>("CategoriesID")
                        .HasColumnType("bigint");

                    b.Property<long>("URLsID")
                        .HasColumnType("bigint");

                    b.HasKey("CategoriesID", "URLsID");

                    b.HasIndex("URLsID");

                    b.ToTable("URLCategoryModelURLModel");
                });

            modelBuilder.Entity("URLShortener.Application.Models.AppIdentityUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("URLShortener.Application.Models.AppRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.Analytics.URLAnalyticsModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastTimeCalculated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MostUsedDevicesJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MostUsedLocationsJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("URLID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("URLID")
                        .IsUnique();

                    b.ToTable("URLAnalytics");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.ClickInfo.ClickInfoModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("ClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeviceInfoID")
                        .HasColumnType("bigint");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LocationID")
                        .HasColumnType("bigint");

                    b.Property<long>("URLID")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("URLID");

                    b.ToTable("Clicks");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.ClickInfo.DeviceInfo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("BrowserFamily")
                        .HasColumnType("text");

                    b.Property<long>("ClickID")
                        .HasColumnType("bigint");

                    b.Property<string>("OSFamily")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ClickID")
                        .IsUnique();

                    b.ToTable("DeviceInfos");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.ClickInfo.LocationInfo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ClickID")
                        .HasColumnType("bigint");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ClickID")
                        .IsUnique();

                    b.ToTable("LocationInfos");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.Finance.DepositModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<long>("FinanceID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RefNumber")
                        .HasColumnType("integer");

                    b.Property<long?>("TrackID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("FinanceID");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.Finance.FinancialRecordModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("FinancialRecords");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.Finance.PurchaseModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomURLID")
                        .HasColumnType("bigint");

                    b.Property<long>("FinanceID")
                        .HasColumnType("bigint");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CustomURLID")
                        .IsUnique();

                    b.HasIndex("FinanceID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.ServiceTariffs.ServiceTariffModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("Price");

                    b.ToTable("ServiceTariffs");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.URL.URLModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMonetized")
                        .HasColumnType("boolean");

                    b.Property<string>("LongURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PurchaseID")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("URLAnalyticsID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ShortCode");

                    b.HasIndex("UserID");

                    b.ToTable("URLs");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.URLCategory.URLCategoryModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("URLCategories");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.User.RefreshToken", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdentityUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.User.UserModel", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FinancialID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("FinancialID");

                    b.ToTable("DomainUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("URLShortener.Application.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("URLShortener.Application.Models.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("URLShortener.Application.Models.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("URLShortener.Application.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("URLShortener.Application.Models.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("URLShortener.Application.Models.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("URLCategoryModelURLModel", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.URLCategory.URLCategoryModel", null)
                        .WithMany()
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("URLShortener.Domain.Entities.URL.URLModel", null)
                        .WithMany()
                        .HasForeignKey("URLsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.Analytics.URLAnalyticsModel", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.URL.URLModel", "URL")
                        .WithOne("URLAnalytics")
                        .HasForeignKey("URLShortener.Domain.Entities.Analytics.URLAnalyticsModel", "URLID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("URL");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.ClickInfo.ClickInfoModel", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.URL.URLModel", "URL")
                        .WithMany("Clicks")
                        .HasForeignKey("URLID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("URL");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.ClickInfo.DeviceInfo", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.ClickInfo.ClickInfoModel", "ClickInfo")
                        .WithOne("DeviceInfo")
                        .HasForeignKey("URLShortener.Domain.Entities.ClickInfo.DeviceInfo", "ClickID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("URLShortener.Domain.Entities.ClickInfo.ClientInfo", "Client", b1 =>
                        {
                            b1.Property<long>("DeviceInfoID")
                                .HasColumnType("bigint");

                            b1.Property<string>("Engine")
                                .HasColumnType("text");

                            b1.Property<string>("EngineVersion")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<bool>("PreventNull")
                                .HasColumnType("boolean");

                            b1.Property<string>("Type")
                                .HasColumnType("text");

                            b1.Property<string>("Version")
                                .HasColumnType("text");

                            b1.HasKey("DeviceInfoID");

                            b1.ToTable("DeviceInfos");

                            b1.WithOwner()
                                .HasForeignKey("DeviceInfoID");
                        });

                    b.OwnsOne("URLShortener.Domain.Entities.ClickInfo.Device", "Device", b1 =>
                        {
                            b1.Property<long>("DeviceInfoID")
                                .HasColumnType("bigint");

                            b1.Property<string>("Brand")
                                .HasColumnType("text");

                            b1.Property<string>("Model")
                                .HasColumnType("text");

                            b1.Property<bool>("PreventNull")
                                .HasColumnType("boolean");

                            b1.Property<string>("Type")
                                .HasColumnType("text");

                            b1.HasKey("DeviceInfoID");

                            b1.ToTable("DeviceInfos");

                            b1.WithOwner()
                                .HasForeignKey("DeviceInfoID");
                        });

                    b.OwnsOne("URLShortener.Domain.Entities.ClickInfo.OSInfo", "OS", b1 =>
                        {
                            b1.Property<long>("DeviceInfoID")
                                .HasColumnType("bigint");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("Platform")
                                .HasColumnType("text");

                            b1.Property<bool>("PreventNull")
                                .HasColumnType("boolean");

                            b1.Property<string>("Version")
                                .HasColumnType("text");

                            b1.HasKey("DeviceInfoID");

                            b1.ToTable("DeviceInfos");

                            b1.WithOwner()
                                .HasForeignKey("DeviceInfoID");
                        });

                    b.Navigation("ClickInfo");

                    b.Navigation("Client");

                    b.Navigation("Device");

                    b.Navigation("OS");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.ClickInfo.LocationInfo", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.ClickInfo.ClickInfoModel", "ClickInfo")
                        .WithOne("PossibleLocation")
                        .HasForeignKey("URLShortener.Domain.Entities.ClickInfo.LocationInfo", "ClickID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClickInfo");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.Finance.DepositModel", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.Finance.FinancialRecordModel", "Finance")
                        .WithMany("Deposits")
                        .HasForeignKey("FinanceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Finance");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.Finance.FinancialRecordModel", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.User.UserModel", "User")
                        .WithOne("FinancialRecord")
                        .HasForeignKey("URLShortener.Domain.Entities.Finance.FinancialRecordModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.Finance.PurchaseModel", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.URL.URLModel", "URL")
                        .WithOne("Purchase")
                        .HasForeignKey("URLShortener.Domain.Entities.Finance.PurchaseModel", "CustomURLID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("URLShortener.Domain.Entities.Finance.FinancialRecordModel", "Finance")
                        .WithMany("Purchases")
                        .HasForeignKey("FinanceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Finance");

                    b.Navigation("URL");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.URL.URLModel", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.User.UserModel", "User")
                        .WithMany("URLs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.URLCategory.URLCategoryModel", b =>
                {
                    b.HasOne("URLShortener.Domain.Entities.User.UserModel", "User")
                        .WithMany("URLCategories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

                modelBuilder.Entity("URLShortener.Domain.Entities.User.RefreshToken", b =>
                    {
                        b.HasOne("URLShortener.Application.Models.AppIdentityUser", null)
                            .WithMany("RefreshTokens")
                            .HasForeignKey("IdentityUserId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

            modelBuilder.Entity("URLShortener.Domain.Entities.User.UserModel", b =>
                {
                    b.HasOne("URLShortener.Application.Models.AppIdentityUser", null)
                        .WithOne("DomainUser")
                        .HasForeignKey("URLShortener.Domain.Entities.User.UserModel", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("URLShortener.Application.Models.AppIdentityUser", b =>
                {
                    b.Navigation("DomainUser");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.ClickInfo.ClickInfoModel", b =>
                {
                    b.Navigation("DeviceInfo");

                    b.Navigation("PossibleLocation");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.Finance.FinancialRecordModel", b =>
                {
                    b.Navigation("Deposits");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.URL.URLModel", b =>
                {
                    b.Navigation("Clicks");

                    b.Navigation("Purchase");

                    b.Navigation("URLAnalytics");
                });

            modelBuilder.Entity("URLShortener.Domain.Entities.User.UserModel", b =>
                {
                    b.Navigation("FinancialRecord")
                        .IsRequired();

                    b.Navigation("URLCategories");

                    b.Navigation("URLs");
                });
#pragma warning restore 612, 618
        }
    }
}
